### ISSUE TITLE
Terminology function: display

### ISSUE THREAD

**Issue by johngrimes** [aehrc/pathling#1066]
```
collection<Coding|CodeableConcept> -> display() : collection<String>
```

This function takes a collection of [Coding](https://pathling.csiro.au/docs/fhirpath/data-types.html#coding) or [CodeableConcept](https://hl7.org/fhir/R4/datatypes.html#CodeableConcept) elements as input, and returns a collection containing the preferred display terms for those codings (according to the terminology server).

Example:

```
Patient.reverseResolve(Condition.subject).code.diplay()
```

**Comment by piotrszul** [comment]
@johngrimes 
I am not sure if it makes sense to apply this function to CodeableConcepts (and by extension to arrays of Codings). 
I think it's different than 'memberOf' or 'translate()' because we would expect a single display name for each coding and it's not obvious what how to combine them for a CodeableConcept (unless we take the first one()). 

Could it be?

`collection<Coding>` -> display() : collection<String>`

**Comment by johngrimes** [comment]
Added in v6.1.0.
