### ISSUE TITLE
Job hangs when terminology service configured but can't connect

### ISSUE THREAD

**Issue by johngrimes** [aehrc/pathling#146]
Steps to reproduce:

1. Configure the terminology service to a server that is not available.
2. Make a request which involves use of the terminology service.
3. Observe that the request hangs indefinitely.

The expected behaviour is that the server would respond immediately with a 503 response code and an OperationOutcome explaining that the connection to the terminology service failed.

**Comment by piotrszul** [comment]
I think the issue is not really so much with Spark as it seem to fail immediately  in this situation but rather with our/hapi exception handling. In particular the exception we are getting is:

```
package ca.uhn.fhir.rest.client.exceptions;

import ca.uhn.fhir.rest.server.exceptions.BaseServerResponseException;
import ca.uhn.fhir.util.CoverageIgnore;

@CoverageIgnore
public class FhirClientConnectionException extends BaseServerResponseException {
  private static final long serialVersionUID = 1L;

  public FhirClientConnectionException(Throwable theCause) {
    super(0, theCause);
  }

  public FhirClientConnectionException(String theMessage, Throwable theCause) {
    super(0, theMessage, theCause);
  }

  public FhirClientConnectionException(String theMessage) {
    super(0, theMessage);
  }
}
```

(that is after unwrapping SparkException). 

which is in a way a malformed `BaseServerResponseException`  in the sense that it has status code 0 which will l be returned to the confused client by default error handling for this type of exceptions.
