### ISSUE TITLE
Null aggregation following aggregation with reverseResolve

### ISSUE THREAD

**Issue by johngrimes** [aehrc/pathling#347]
Given the following query:

`POST /Patient/$aggregate`

```json
{
  "resourceType": "Parameters",
  "parameter": [
    {
      "name": "aggregation",
      "valueString": "reverseResolve(Condition.subject).count()"
    },
    {
      "name": "aggregation",
      "valueString": "count()"
    }
  ]
}
```

We would expect the following result:

```json
{
  "resourceType": "Parameters",
  "parameter": [
    {
      "name": "grouping",
      "part": [
        {
          "name": "result",
          "valueUnsignedInt": 71
        },
        {
          "name": "result",
          "valueUnsignedInt": 9
        }
      ]
    }
  ]
}
```

Instead we get the following:

```json
{
  "resourceType": "Parameters",
  "parameter": [
    {
      "name": "grouping",
      "part": [
        {
          "name": "result",
          "valueUnsignedInt": 71
        },
        {
          "name": "result"
        }
      ]
    }
  ]
}
```

**Comment by johngrimes** [comment]
I've added a failing test to the branch `issue/347`.

**Comment by piotrszul** [comment]
So I am starting to believe that this is actually bug in our code, related to joining of aggregations (possibly in the context of not groupings) and the indeterministic nature of calling first() on an unordered column. 
This issue does appear even with master='local[1]' as long as there is more than one partition in resource datasets. 
Ultimately we do:

```
LEFT OUTER JOIN  ON first(Patient.id) == first((Patient joined with Condition).id) 
```
And think they are just different (because they are not deterministic) so we are getting NULL as the value of the second aggregation.,

Need to confirm that but I am 50% confident this it the source of this issue.
