### ISSUE TITLE
HTML rendering of resource shows incorrect Content-Type

### ISSUE THREAD

**Issue by johngrimes** [aehrc/pathling#70]
To reproduce:

1. Visit https://pathling.csiro.au/fhir/OperationDefinition/aggregate-2 using a browser.
2. Observe that the `Content-Type` in the "Response Headers" section is `application/fhir+xml;charset=utf-8`, while the "Response Body" is JSON.

If you click on the "HTML JSON" or "HTML XML" links, the `Content-Type` appears to be set correctly.

**Comment by piotrszul** [comment]
This is an issue with: ```ca.uhn.fhir.rest.server.interceptor.ResponseHighlighterInterceptor```
It uses different mechanism to determine determine encoding for embedding  response in HTML and for outputting the supposed response Content-Type.  In particular the second one is determined by the  content of "Accept: " request header. ```html/xml``` is selected because it's (in Chrome) it's explicitly accepted with high priority.

**Comment by piotrszul** [comment]
This would have to be fixed in HAPI (?) or maybe we could create copy of this interceptor.

**Comment by johngrimes** [comment]
Thanks @piotrszul, perhaps we should create a new issue/PR with hapi-fhir?

**Comment by johngrimes** [comment]
Re-tested on v3 branch - this has now been fixed.
